language: python
python: 3.8
branches:
  only:
  - master
addons:
  ssh_known_hosts:
    secure: xlF8qz/IBzghSQn0WYZFMfd0TlQDtIXC1HauMHXR1qRXLJmlWQTOpJNyXpIFSvnwLY9YXMCveRRZyE/wptEhFlXnla0tKTY7uv6ccNwIckJbeq55T7Pd4zMiePU3kGAVkBd9wj/4HG2dPqCWEIX+ZnEtFYxMfr2GOeD0XtsBUK2n7zU2hZVzjCvYbphv6XNFjp0KJQEwA166TNIwsO5r7msU88gPM9dIoxOAgfeT+d46m/bm0mNqw0qO7WarBWxOAPDVZPKzawe+nX5h2YJcqlxLfci1xtllhu1PloA6q2vzOgt5Zce4LFbHBxqm673zeG9maDZ9WqpMN+V1/JNiUEoE8dzwnQrK2WB5pBcEN1Ou/Dw8IbRr3taypggd8O7QPWHKnh1qyqlZiKkhrMiiNoFEtdu/6uID+z1fVUpj6pRnEUhD8NGIVnmHmo2joW/jjaCXzUAw987fyg+yDJhwXrhv6RbdBHUlDltbY0qgYgb4mIRyJadtrckfTW4KWivbzqNlpk9d8zYE6OItEM4iz9dTFR42Drp2Xb3LONjI+eD3H6XpUKOqi9zSVVI26fHD34I35xf8ALHHs5aSiDcI0pusvE8AukwJC/iVV66mxkk2jAUGvDUVrFCuYHVvjJhgsaXO2Dn3mYtHX3C7MHNRmrN9FktIeHAz3wsH8rzZbz4=
install: pip install -r requirements.txt
script: python manage.py test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - cp .travis/deploy_rsa ~/.ssh/deploy_rsa
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
notifications:
  email: false
  slack:
    rooms:
      secure: 0E+motYdvv0arhKyTc/8j4FoJ3YtfOmawb3XmI22Ml2C5gowlEKZSVb02B3NyOj6AuO/wiFJUw+CBnqo9LLx4qssSUyk1MpN86Z4xFQcUFPaMn/Gt/fAhUyy+s19RqWM/ZM8BXUKWE04xKbrVwbrbRcLdS5z+8mwe8QkSYbSes6JLbzX/PkaPTfsCgvtX+zXgVz6oEnnWGZ0yzZtWhkTsOEaW1arLC1xJOglSERVl0MDYmycPnws0pbkx9w2oIT68ROPdZoREP4eYhYeU7TZIqJlZ/o8MUcz6jMGw1BjH2B52Kk7wkWv4aeB2yY+X8e9zfNN2A7J8iwhqADoWFimdNxR8cry25xbx38gCSSKubVmSnmgMBSl3XuGE7p3b5Ld25R22QEN+MeG14tr+6NZZeR5nR0JixZzeCmztiouX1HbUDDLHhBQgtpEecX+l00OlsvKExa/CO5pmrLlg+S4AUtg4kSpxuxfc0DB9/MSa7GSF1DKWoaD1zIDqzAG/SUVZDbUf9BpBaIZk4pCAp+eXfl9QG8hctGem0YuaqgIar4ox83LXIQgmzolGRw52cKKmCyEJAFjh/26E7ONsd3Vkmk7qd52GpphZOEk/J/fKmz64NSQ60I+fZjjAoFW9eLhRKa/Q0dyctqqlqoDMJbLInQJIJY7fW6QK+4p1odaB+A=
